version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      include: scope
      prefix: chore
      prefix-development: chore

  - package-ecosystem: npm
    directories:
      - /packages/docs
      - /packages/example
    schedule:
      interval: weekly
    commit-message:
      include: scope
      prefix: chore
      prefix-development: chore
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-major]
